module.exports = {
    TW :{
        buy:"购买",
        buyMonthCardContent:"恭喜你购买月卡成功",
        firstBuy:"首充购买赠送",
        buySuccessTheme : "购买成功",
        fromShop : "商城",
        bossTheme :"世界BOSS奖励",
        bossContent : "击杀世界BOSS",
        fromBoss : "世界BOSS",
        arenaTheme:"竞技场奖励",
        arenaContent:"竞技场挑战奖励",
        arenaContent1:"竞技场排名首次晋升至第",
        fromArena:"竞技场",
        keysTheme:"兑换券",
        keysContent:"获得兑换道具"
    },
    chinese :{
        buy:"购买",
        buyMonthCardContent:"恭喜你购买月卡成功",
        firstBuy:"首充购买赠送",
        buySuccessTheme : "购买成功",
        fromShop : "商城",
        bossTheme :"世界BOSS奖励",
        bossContent : "击杀世界BOSS",
        fromBoss : "世界BOSS",
        arenaTheme:"竞技场奖励",
        arenaContent:"竞技场挑战奖励",
        arenaContent1:"竞技场排名首次晋升至第",
        fromArena:"竞技场",
        keysTheme:"兑换券",
        keysContent:"获得兑换道具"
    },
    VN :{
        buy:"Mua",
        buyMonthCardContent:"Chúc mừng đã mua thẻ tháng",
        firstBuy:"Nạp lần đầu mua tặng",
        buySuccessTheme : "Đã mua",
        fromShop : "Shop",
        bossTheme :"Quà Boss Thế Giới",
        bossContent : "Diệt Boss Thế Giới",
        fromBoss : "BOSS",
        arenaTheme:"Quà đấu trường",
        arenaContent:"Quà chiến đấu trường",
        arenaContent1:"Hạng đấu trường lần đầu tăng đến hạng",
        fromArena:"Đấu trường",
        keysTheme:"Phiếu đổi",
        keysContent:"Nhận vật phẩm đổi"
    }
};