var CONSTS = require('./../consts/consts');

module.exports = {
    onServerErr : {
        NotValid :"onServerErr",
        NotValidArgs :{"code":CONSTS.EVENT.NOTVALID},
        NotLogin : "onServerErr",
        NotLoginArgs:{"code":CONSTS.EVENT.NOTLOGIN}
    },
    clientEvent :{
        onRegisterSuccess:"onRegisterSuccess",
        onRegisterFail: "onRegisterFail",
        onLoginSuccess: "onLoginSuccess",
        onLoginFail:"onLoginFail",
        onBroadcast : "onBroadcast",
        onReqAvatarListSuccess: "onReqAvatarListSuccess",
        onReqAvatarListFail: "onReqAvatarListFail",
        onCreateAvatarSuccsess : "onCreateAvatarSuccsess",
        onCreateAvatarFail : "onCreateAvatarFail",
        onPlayerExecutive : "onPlayerExecutive",
        onTimestamp : "onTimestamp",
        onNewMails : "onNewMails",
        onMercenaryConfig : "onMercenaryConfig",
        onEctypeConfig : "onEctypeConfig",
        onBossConfig : "onBossConfig",
        onDropoutConfig : "onDropoutConfig",
        onEpxConfg : "onEpxConfg",
        onMainichiConfig : "onMainichiConfig",
        onReqBoss : "onReqBoss",
        onAttakedBoss : "onAttakedBoss",
        onBossScore : "onBossScore",
        onBossRewardList : "onBossRewardList",
        onRandomPlayer : "onRandomPlayer",
        onExistNickname : "onExistNickname",
        onNotExistNickname:"onNotExistNickname",
        onWorldMap: "onWorldMap",
        onRefLogs: "onRefLogs",
        onCurrVersion:"onCurrVersion",
        onLumiSignSuccess : "onLumiSignSuccess",
        onLumiSignFail : "onLumiSignFail",
        onUpgrade : "onUpgrade",
        onLegend  : "onLegend",
        onAggregateConsumption:"onAggregateConsumption",
        onPlayerRank : "onPlayerRank",
        onFrlist : "onFrlist",
        combatPval : "combatPval",
        combatPvalRank : "combatPvalRank",
        bossRank : "bossRank",
        bindSuccess : "bindSuccess",
        bindFail : "bindFail",
        onRepeat : "onRepeat",
        onUnique : "onUnique",
        onArenaRank : "onArenaRank",
        onArenaListPlayer:"onArenaListPlayer",
        onArenaPlayerRank:"onArenaPlayerRank",
        onArenaScore : "onArenaScore",
        onArenaLogs : "onArenaLogs",
        onPidLoadPlayer : "onPidLoadPlayer",
        onNameLoadPlayer:"onNameLoadPlayer",
        onSignConfig : "onSignConfig",
        onPropsOut :"onPropsOut",
        onPropsUse :"onPropsUse",
        onSettleArenaAward:"onSettleArenaAward",
        onArenaAward:"onArenaAward",
        onRealArenaAward:"onRealArenaAward",
        onUseKey : "onUseKey",
        onNotice : "onNotice",
        onSvrList : "onSvrList",
        onSvrStatus:"onSvrStatus",
        onUpPass : "onUpPass",
        onPassRank : "onPassRank",
        onIAPverify:"onIAPverify",
        onUpLv : "onUpLv",
        onAsdkLogin:"onAsdkLogin",
        onUpdatePass:"onUpdatePass",
        onEsdkLogin:"onEsdkLogin",
        onSMsdkLogin:"onSMsdkLogin",
        onSMGameSign:"onSMGameSign"
    }
};